### ISSUE TITLE
Add support for --verbose flag

### ISSUE THREAD

**Issue by cherryramatisdev** [lanjoni/hackacrow#11]
Sometimes we want to see what form the INPUT is being passed on the test runs, this has proven really useful in some PRs on the he4rtoberfest repo

![image](https://github.com/lanjoni/hackacrow/assets/86631177/72f7687c-0e40-4416-a7fa-b8ccab55dc3a)

**Comment by vitorsantanna2** [comment]
https://github.com/lanjoni/hackacrow/pull/14

**Comment by lanjoni** [comment]
Solved https://github.com/lanjoni/hackacrow/pull/14!
