### ISSUE TITLE
Alternative JSON flag

### ISSUE THREAD

**Issue by lanjoni** [lanjoni/hackacrow#3]
It's not always practical for JSON files for programming languages and tests to be together in the same place, right? Well, the programming language is fine, but the tests themselves would be interesting to be able to provide any custom tests that you want to use without necessarily using a directory within the repository!

The purpose of this issue is to discuss the development of a flag to inform the path of the JSON file to be read for tests, that is, the `expect.json` file, informing the expected inputs and outputs!

**Comment by J0sueTM** [comment]
Hey @lanjoni, just to make things clear, this change would be available only to the administrators of the hackacrow instance, right? Because if not, there would be security implications since the common user would be able to bypass which tests are being run, making the check itself volatile.

Besides that, do you think a `-e /random/dir/my_expect.json` would be enough? In case yes, these minor requirements should be thought:
- Make sure to check for syntax errors in the file
- Should there be a minimum of maximum of tests per exercise?
- Should the exercise suite be in pair (by amount) to the default amount? e.g. there're 11 exercises in the default exercise suite, should the be 11 as well or they're not correlated at all?

**Comment by lanjoni** [comment]
> Hey @lanjoni, just to make things clear, this change would be available only to the administrators of the hackacrow instance, right? Because if not, there would be security implications since the common user would be able to bypass which tests are being run, making the check itself volatile.
> 
> Besides that, do you think a `-e /random/dir/my_expect.json` would be enough? In case yes, these minor requirements should be thought:
> 
>     * Make sure to check for syntax errors in the file
> 
>     * Should there be a minimum of maximum of tests per exercise?
> 
>     * Should the exercise suite be in pair (by amount) to the default amount? e.g. there're 11 exercises in the default exercise suite, should the be 11 as well or they're not correlated at all?

Firstly, thank you very much for the answer! Know that I'm here to help you with any questions you may have during development!

Well, first of all, it is necessary to point out something that may not have been clear: hackacrow is a general purpose project, not specifically to be used on just one occasion, that is, it is a project to be developed and applied to several other occasions. projects for testing.

That said, I believe so, the point of adding a flag with the path to the test JSON file is wonderful and is exactly what we need.

What the specific flag would be has not yet been defined, however, I believe we can address this during development. Well, now to answer your questions:
- "Make sure to check for syntax errors in the file": yes, we need to validate the syntax of the input JSON, so I'm thinking about creating an `expect.example.json`, what do you think?
- "Should there be a minimum of maximum of tests per exercise?": no, the number of tests to be performed is undefined (still, and I hope it can stay that way so we don't worry for now)!
- "Should the exercise suite be in pair (by amount) to the default amount? e.g. there're 11 exercises in the default exercise suite, should the be 11 as well or they're not correlated at all?": no, a number of exercises as well as the number of tests is undefined and may vary, considering that the `expect.json` model is nothing more than an array of values, which is why the exercises are categorized in numbers.

I hope I have clarified some points and know that I am here for any help! Thank you very much in advance!

**Comment by lanjoni** [comment]
Closed https://github.com/lanjoni/hackacrow/pull/5
