### ISSUE TITLE
Spec tests for everyone

### ISSUE THREAD

**Issue by lanjoni** [lanjoni/hackacrow#4]
The creation of tests is what shapes the development of this CLI, after all, the objective of hackacrow is to be a tool that improves your tests in a practical way.

Therefore, I am looking for contributions that formulate tests for the repository, aiming for safe development and allowing more people to contribute!

If you are interested in better understanding how tests work within Crystal, I recommend accessing the [official document](https://crystal-lang.org/reference/1.9/guides/testing.html), which specifies the use of the [spec library](https://crystal-lang.org/api/1.9.2/Spec.html)!

**Comment by igorwessel** [comment]
@lanjoni Lately I've been learning crystal through the doc, and I never thought about how testing tools are made using JSON.

I would like to try implementing the tests :)

**Comment by igorwessel** [comment]
@lanjoni I took a look at the code and do we intend to separate generating output from the validations? example:
https://github.com/lanjoni/hackacrow/blob/abdb64f38c595ec6d5e96662bc1c840d199652ed/src/run.cr#L26-L35

**Comment by lanjoni** [comment]
> @lanjoni I took a look at the code and do we intend to separate generating output from the validations? example:
> 
> https://github.com/lanjoni/hackacrow/blob/abdb64f38c595ec6d5e96662bc1c840d199652ed/src/run.cr#L26-L35

Awesome! First of all, I would like to thank you for being interested in contributing, so please know that I am here for any questions you may have, ok?

Well, about the issue of testing with spec. I believe that *this* issue itself is not exactly about dealing with the specific tests of the exercises, but rather about the implementation tests of the hackacrow itself.

The spec tests I mentioned are related to testing to ensure that nothing within hackacrow broke with contributions coming in, being useful for validating future commits and pull requests.

Hackacrow is designed to be a testing tool, hence the confusion, but the tests I'm referring to are about the features that Hackacrow offers.

Example:
- Flag test to check if they are all validating correctly
- Testing commands to see if JSON parse works normally
- Testing programming languages to verify that they are working properly

These are the tests that need to be developed in [`./spec`](https://github.com/lanjoni/hackacrow/tree/main/spec). Do you believe you can develop some test specs? If you need, I can help you with this issue!

**Comment by igorwessel** [comment]
Thanks for explanation!
I will try to make tests! any problems/questions I will mark you through draft PR.

**Comment by lanjoni** [comment]
Perfect! Can I assign the issue to you @igorwessel?

**Comment by igorwessel** [comment]
Sure! 👍

**Comment by lanjoni** [comment]
Thanks @igorwessel! Closed with https://github.com/lanjoni/hackacrow/pull/6!
