### ISSUE TITLE
Improve support for C languages

### ISSUE THREAD

**Issue by cherryramatisdev** [lanjoni/hackacrow#9]
The lang spec for c and c++:

```
  "c": "gcc $ -o a.out && ./a.out",
  "cpp": "g++ $ -o a.out && ./a.out",
```

We need to substitute `$` with the file instead of just appending like we do today

File to modify: https://github.com/cherryramatisdev/hackacrow/blob/47736a92522a4dd668f342eedbd4c598f4994b60/src/run.cr#L35

**Comment by vitorsantanna2** [comment]
Now that I saw that they had already resolved this issue

**Comment by lanjoni** [comment]
Thanks for the contribution @cherryramatisdev! If you believe that this issue is resolved, you can close it now. Soon we can discuss other types of improvements with compiled languages, what do you think?

**Comment by cherryramatisdev** [comment]
Sounds good to me!
